version: "3.8"
   

services:
  web:
    container_name: insurance
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - elasticsearch


  postgres:
    container_name: pg14
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:${PGDATA}
    restart: unless-stopped


  elasticsearch:
    container_name: es
    image: elasticsearch:7.17.0
    env_file:
      - .env
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data


volumes:
  postgres-data:
  admin-data:
  es-data: