version: "3.8"
   

services:
  web:
    container_name: insurance
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch


  postgres:
    container_name: pg14
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:${PGDATA}
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - admin-data:/var/lib/pgadmin
    restart: unless-stopped

  elasticsearch:
    container_name: es
    image: elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data


volumes:
  postgres-data:
  admin-data:
  es-data: